topgquotes = [
    "Stop whining and start winning.",
    "Excuses are for losers, actions are for champions.",
    "Mediocrity is for the weak, greatness is for the brave.",
    "No one cares about your feelings, only your results.",
    "Dreams don't work unless you do.",
    "Pain is temporary, quitting lasts forever.",
    "Your comfort zone is a prison, break free.",
    "If you want it, stop talking and start hustling.",
    "Success is earned, not given.",
    "Stop being a victim, be a victor.",
    "Self-pity is a disease, eliminate it.",
    "Complacency is the enemy of progress.",
    "Hard work beats talent when talent doesn't work hard.",
    "You're not a product of your circumstances, but of your decisions.",
    "Losers focus on problems, winners focus on solutions.",
    "There's no shortcut to success, only hard work.",
    "If you don't risk anything, you risk everything.",
    "Fear is a choice, so is courage.",
    "To win, you must first conquer yourself.",
    "Don't wait for opportunity, create it.",
    "Stop blaming others for your failure, take responsibility.",
    "A dream without action is just a fantasy.",
    "The world owes you nothing, go get what you want.",
    "Your life is in your hands, stop wasting it.",
    "If you want to fly, stop hanging with chickens.",
    "You'll never succeed if you're scared to fail.",
    "Stop waiting for the perfect moment, it doesn't exist.",
    "The only limits you have are the ones you create.",
    "Those who can't handle the truth will always fail.",
    "Your time is limited, don't waste it living someone else's life.",
    "Only the strong survive in this world.",
    "The harder you work, the luckier you get.",
    "Success demands sacrifice, are you willing to pay the price?",
    "You don't deserve anything, you earn it.",
    "You're either moving forward or falling behind.",
    "If you're not growing, you're dying.",
    "Stop dreaming, start doing.",
    "The only difference between a winner and a loser is mindset.",
    "Winners take action, losers make excuses.",
    "Your best teacher is your last mistake.",
    "Doubt kills more dreams than failure ever will.",
    "The only thing standing in your way is you.",
    "You can't change your past, but you can create your future.",
    "You get what you tolerate, so don't tolerate mediocrity.",
    "The weak will always envy the strong.",
    "The only way to achieve the impossible is to believe it's possible.",
    "Discipline is the bridge between goals and accomplishment.",
    "Be willing to walk alone to reach your destination.",
    "If you're not willing to fight for it, you don't deserve it.",
    "There are no failures, only lessons.",
    "Don't be a spectator, be a competitor.",
    "Procrastination is the thief of time and success.",
    "If it was easy, everyone would do it.",
    "Success isn't for the weak-minded.",
    "If you don't grind, you don't shine.",
    "It's not about talent, it's about effort.",
    "You can't climb the ladder of success with your hands in your pockets.",
    "Losers quit when they're tired, winners quit when they've won.",
    "The road to success is paved with obstacles, learn to overcome them.",
    "There's no traffic on the extra mile.",
    "Success starts when you stop making excuses.",
    "You are the architect of your own destiny.",
    "The pain of discipline is far less than the pain of regret.",
    "The only way to fail is to quit.",
    "Comfort is the enemy of progress.",
    "The world doesn't reward average.",
    "Every failure brings you one step closer to success.",
    "You are your own biggest obstacle.",
    "Dreams die when you lack discipline.",
    "To achieve greatness, you must first become uncomfortable.",
    "Your attitude determines your altitude.",
    "If you don't challenge yourself, you don't change.",
    "Aim for progress, not perfection.",
    "Your worth is defined by your actions, not your words.",
    "You can't cheat the grind, it knows how much you've invested.",
    "To be the best, you have to beat the best.",
    "Your success is determined by your daily choices.",
    "Change is inevitable, growth is optional.",
    "Your habits define your future.",
    "You can't expect to succeed if you only work on the days you feel like it.",
    "The more you sweat in training, the less you bleed in battle.",
    "Don't fear failure, fear being in the same place next year.",
    "Success is a decision, not a gift.",
    "Stop wishing for it, start working for it.",
    "The only thing you deserve is what you earn.",
    "If you don't prioritize your life, someone else will.",
    "If you don't stand for something, you'll fall for anything.",
    "Your life is a reflection of your choices.",
    "Don't wish it were easier, make yourself better.",
    "Nothing worth having comes easy.",
    "You become what you believe.",
    "If you don't make time for success, you'll make time for failure.",
    "You are the average of the five people you spend the most time with.",
    "Without struggle, there is no progress.",
    "You can't change your future, but you can change your habits, and your habits will change your future.",
    "The best revenge is massive success.",
    "You can't win in life if you're losing in your mind.",
    "Stop waiting for permission, take control of your life.",
    "The size of your success is determined by the size of your belief.",
    "The moment you give up is the moment you let someone else win.",
]
